# Generated by Django 4.0.3 on 2023-03-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=140)),
                ('Timestamp', models.DateTimeField(blank=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
