# Generated by Django 4.0.3 on 2023-03-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_aboutcorousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutLibrarian',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BooksNewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
