# Generated by Django 4.1.7 on 2023-03-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_booksnewarrival'),
        ('staff', '0004_aboutlibrarian_abouttext_booksnewarrival'),
    ]

    operations = [
    ]
