# Generated by Django 4.1.7 on 2023-03-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_merge_20230329_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksTopPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
